#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu
# container’s Nginx installation from listening on port 80.
# Then, write a Bash script with the minimum number of commands to automate your fix.

mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start
