#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving
#   a SIGQUIT or SIGTERM signal

file_name="/var/run/myscript.pid"

pgrep -f "$0" > "$file_name"

# This command does the same as above
#echo $$

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; rm $file_name; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm $file_name; exit' SIGQUIT
done

