#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd

# used underscores to pass SHELLCHECK SC2034 unused variable error
# while IFS=":" read -r username password uid gid fullname homedir shell; do
while IFS=":" read -r username _ uid _ _ homedir _; do
    echo "$username:$uid:$homedir"
done < "/etc/passwd"