#!/usr/bin/env bash
# script that displays:
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is displayed

contents=$(ls)

for content in $contents; do
    new_name=${content##*-}
    echo "$new_name"
done